[package]
name = "delay-pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
libc = "0.2"
notify = "8.0"
tokio = { version = "1.44", features = ["full"] }

[dev-dependencies]
rand = "0.9"
tempfile = "3.19"
